### ISSUE TITLE
Instructor search bug

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#924]
### Steps to Reproduce

1. Visit https://ocw.mit.edu/courses/18-086-mathematical-methods-for-engineers-ii-spring-2006/
2. Click "Gilbert Strang" in course info

### Expected Behavior
Navigates to search page for Gilbert Strang, namely https://ocw.mit.edu/search/?q=%22Prof.%20Gilbert%20Strang%22

### Actual Behavior

Briefly navigates to the correct page, then URL updates to https://ocw.mit.edu/search

https://user-images.githubusercontent.com/9010790/197210911-ec9b92f1-21b2-462a-bfd1-df52231bbe17.mov

### Other Notes
We should check whether this is happening for other links. It appears not to happen for "department" in course info, at least.

**Comment by ChristopherChudzicki** [comment]
Fixed on main, though not released yet.

**Comment by pdpinch** [comment]
This is still broken. 

For example, on https://ocw.mit.edu/courses/11-139-the-city-in-film-spring-2015/ the instructor link goes to https://ocw.mit.edu/search?t=Ezra+Haber+Glenn

What do we need to do to fix it?

**Comment by ChristopherChudzicki** [comment]
@pdpinch The course just needs to be re-published. I'm not sure why there wasn't a mass build when the release went through. Looking into it.

**Comment by ChristopherChudzicki** [comment]
@pdpinch All sites have been re-published, so has now gone out.

We realized this morning that none of the ocw-hugo-themes releases in the last week have triggered mass publishes. The fundamental issues that caused this were, imo:
1. A lack of notifications when the theme-assets pipeline fails, combined with
2. a misunderstanding on my part

I've opened https://github.com/mitodl/ocw-studio/issues/1558 in regards to (1). I think the wording of the error message could possibly help prevent (2) in future.
